builds:
  -
     ldflags:
       - -s -w -X cmd.version={{.Version}} -X cmd.commit={{.Commit}} -X cmd.date={{.Date}} -X cmd.builtBy=elhmn

brews:
  - tap:
      owner: elhmn
      name: ckp
    folder: Formula
    homepage: https://github.com/elhmn/ckp
