name: Lint

on:
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses:
          actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run lint
        run: make lint
